### basic settings

# site properties and page defaults
title: Witch Lab
description: Using synthetic biology tools to understand and rewire cellular behavior
logo: images/FlaskLogoFullLight.svg
logo-text: false
header: images/background.jpg
footer: images/background.jpg
baseurl: /witchlab

# site social media and other links
links:
  email: weinberz@gmail.com
  google-scholar: Zara Weinberg
  github: weinberz
  twitter: weinberz

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
